version: "3.10"

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: app_fastapi:0.0.1-dev
    container_name: app_fastapi
    command: bash docker/runserver.sh
    env_file:
      - .env
    volumes:
      - .:/home/appuser/app

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: app_fastapi_tests:0.0.1-dev
    container_name: app_fastapi_tests
    env_file:
      - .env
    volumes:
      - .:/home/appuser/app
    command: [ "pytest" ]