"""create_table

Revision ID: bf8039c39e47
Revises: b2805ea27732
Create Date: 2023-08-04 19:27:20.996150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8039c39e47'
down_revision = 'b2805ea27732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_results', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_results', 'timestamp')
    # ### end Alembic commands ###
